[sources.docker_logs]
type = "docker_logs"

[sinks.axiom]
type = "http"
uri = "https://eu-central-1.aws.edge.axiom.co/v1/ingest/lexibot"
encoding.codec = "json"
headers.Authorization = "${AXIOM_BEARER_TOKEN}"
headers.Content-Type = "application/json"
